default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud auth activate-service-account --key-file "$SERVICE_ACCOUNT"
    - gcloud config set project ptbudimas

build:
  stage: build
  script:
    - gcloud builds submit --config=cloudbuild.yaml --substitutions=_LOCATION="asia-southeast2",_REPOSITORY="fe-sales-canvas",_IMAGE="fe-sales-canvas"

deploy:
  stage: deploy
  script:
    - gcloud run deploy budimas-sales-canvas --image asia-southeast2-docker.pkg.dev/ptbudimas/fe-sales-canvas/fe-sales-canvas --region=asia-southeast2 --platform managed --allow-unauthenticated